[package]
name = "ultimdos"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_mc_proto = "0.1.8"
serde_json = "1.0.117"
socks = "0.2.3"
rand = "0.8.5"
uuid = { version = "1.8.0", features = ["v3"] }
md5 = "0.7.0"
dns-lookup = "2.0.4"
